### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Sgsouham**

### CODE REVIEW

**Comment by ucalyptus** [comment]
@Sgsouham Appendix has some important info, it would be great if u annotate some of that too.

**Comment by Sgsouham** [comment]
okay. Will do.

**Comment by ucalyptus** [comment]
@Sgsouham crop the appendix and references since that's unnecessary. saves MB storage. Will merge after that

**Comment by Sgsouham** [comment]
Okay.

**Comment by Sgsouham** [comment]
Check

**Pull request merged**
