### PR TITLE
Add VirTex

### PR DESCRIPTION
**Pull request by parmarsuraj99**
Added annotated pdf of VirTex [https://arxiv.org/abs/2006.06666](https://arxiv.org/abs/2006.06666) with cropped appendix and references.

### CODE REVIEW

**Review by ucalyptus — APPROVED** [review]
@parmarsuraj99  I have approved this PR. you can update the readme with your entry now in this PR. I will merge once that is done.

**Comment by parmarsuraj99** [comment]
@ucalyptus Should the Image for .xopp be removed as we are now uploading .pdf directly?

**Comment by ucalyptus** [comment]
@parmarsuraj99 yes let's delete that and put a gif of various annotated pdf pages. Looks good.
Also dont forget to update the table with your entry.

**Comment by ucalyptus** [comment]
@parmarsuraj99 we will look into the gif thing later . Merging it for now. the gif will look cool , see aakash nain's repo fr example.

**Pull request merged**
